# Generated by scripts/generate_models.py. Do not edit.
import datetime
import uuid
from typing import Any, Optional

from pgvector.sqlalchemy.vector import VECTOR
from sqlalchemy import (
    DateTime,
    ForeignKeyConstraint,
    Index,
    Integer,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Documents(Base):
    __tablename__ = 'documents'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='documents_pkey'),
        UniqueConstraint('source', name='uq_documents_source'),
        Index('ix_documents_created_date', 'created_date')
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    ingestion_status: Mapped[str] = mapped_column(String(20), nullable=False, server_default=text("'pending'::character varying"))
    created_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    last_modified_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    embedding_model: Mapped[Optional[str]] = mapped_column(String(100))

    parent_chunks: Mapped[list['ParentChunks']] = relationship('ParentChunks', back_populates='document')


class ParentChunks(Base):
    __tablename__ = 'parent_chunks'
    __table_args__ = (
        ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE', name='parent_chunks_document_id_fkey'),
        PrimaryKeyConstraint('id', name='parent_chunks_pkey'),
        UniqueConstraint('document_id', 'position', name='uq_parent_chunks_document_position'),
        Index('ix_parent_chunks_created_date', 'created_date')
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    document_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    text_: Mapped[str] = mapped_column('text', Text, nullable=False)
    created_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    last_modified_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    source_location: Mapped[Optional[str]] = mapped_column(Text)

    document: Mapped['Documents'] = relationship('Documents', back_populates='parent_chunks')
    child_chunks: Mapped[list['ChildChunks']] = relationship('ChildChunks', back_populates='parent')


class ChildChunks(Base):
    __tablename__ = 'child_chunks'
    __table_args__ = (
        ForeignKeyConstraint(['parent_id'], ['parent_chunks.id'], ondelete='CASCADE', name='child_chunks_parent_id_fkey'),
        PrimaryKeyConstraint('id', name='child_chunks_pkey'),
        UniqueConstraint('parent_id', 'position', name='uq_child_chunks_parent_position'),
        Index('ix_child_chunks_created_date', 'created_date'),
        Index('ix_child_chunks_embedding_hnsw', 'embedding'),
        Index('ix_child_chunks_text_fts')
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    parent_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    text_: Mapped[str] = mapped_column('text', Text, nullable=False)
    embedding: Mapped[Any] = mapped_column(VECTOR(1536), nullable=False)
    created_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    last_modified_date: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    source_location: Mapped[Optional[str]] = mapped_column(Text)

    parent: Mapped['ParentChunks'] = relationship('ParentChunks', back_populates='child_chunks')
