"""add child text fulltext index

Revision ID: 4ad46fb21006
Revises: 65caeeab7ecf
Create Date: 2026-09-24 18:46:28.377449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4ad46fb21006'
down_revision: Union[str, Sequence[str], None] = '65caeeab7ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_child_chunks_text_fts', 'child_chunks', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_child_chunks_text_fts', table_name='child_chunks', postgresql_using='gin')
    # ### end Alembic commands ###
