"""Generate ORM models from the migrated PostgreSQL schema."""

from pathlib import Path

import pgvector.sqlalchemy  # Register vector types for reflection.
from core.db import get_engine
from sqlacodegen.generators import DeclarativeGenerator
from sqlalchemy import MetaData

OUTPUT = Path(__file__).resolve().parents[1] / "models.py"


def main() -> None:
    engine = get_engine()

    try:
        metadata = MetaData()
        metadata.reflect(
            bind=engine, only=["documents", "parent_chunks", "child_chunks"]
        )
        code = DeclarativeGenerator(metadata, engine, options=[]).generate()

        OUTPUT.write_text(
            "# Generated by scripts/generate_models.py. Do not edit.\n" + code,
            encoding="utf-8",
        )

        print(f"Generated {OUTPUT}")
    finally:
        engine.dispose()


if __name__ == "__main__":
    main()
